---
title: "Data Modeling"
output: html_notebook
---

# Loading in Data and packages

```{r}
load("data/ess.Rdata")

pacman::p_load(tidyverse, writexl, haven, sjPlot, sjmisc, texreg, car, psych, knitr, labelled, broom, magrittr, BaylorEdPsych, lmtest, datapasta, brms, questionr, lavaan, car, BBmisc, stargazer, caret, DescTools, rcompanion, tidyeval, mgcv, countrycode)

#pacman::p_install_gh("wilkelab/cowplot")
#devtools::install_github("gadenbuie/regexplain")

range01 <- function(x){(x - min(x, na.rm = T)) / (max(x, na.rm = T) - min(x, na.rm = T))}
```








# Data prep

```{r}
#load("data/ess.Rdata")
#binoculaR::binoculaR(ess)


# 1025	impsafe	Important to live in secure and safe surroundings
# 1027	ipfrule	Important to do what is told and follow rules
# 1036	ipbhprp	Important to behave properly
# 1040	imptrad	Important to follow traditions and customs
# 1034	ipstrgv	Important that government is strong and ensures safety

# 1197	wmcpwrk	Women should be prepared to cut down on paid work for sake of family
# 1198	mnrgtjb	Men should have more right to job than women when jobs are scarce

mlogit_ess <- ess %>% 
  mutate(target = as.factor(target)) %>% 
#  drop_na(target) %>% 
  mutate(imm_culture = 10 - imueclt) %>% 
  mutate(imm_badecon = 10 - imbgeco) %>%
  mutate(imm_worselive = 10 - imwbcnt) %>%
  mutate(econ_unsat = 10 - stfeco) %>% 
  mutate(aut_safe = 7 - impsafe) %>% 
  mutate(aut_rules = 7 - ipfrule) %>%
  mutate(aut_behave = 7 - ipbhprp) %>%
  mutate(aut_trad = 7 - imptrad) %>% 
  mutate(aut_govstrong = 7 - ipstrgv) %>% 
  rename(
    econ_insec = hincfel,
    demsat = stfdem,
    age = agea,
#    year = inwyys,
    trust_un = trstun,
    trust_eu = trstep,
    trust_gov = trstplt,
    # trust_parliament = trstprl,
    # trust_police = trstplc,
    # trust_courts = trstlgl,
    stfgov = stfgov,
    religion = rlgdgr,
    rural = domicil
 #   educ = edulvlb
  ) %>%
  mutate(
    cntry = cntryname,
    educ = ifelse(eisced == 55, NA, eisced),
    work = ifelse(mnactic == 1, 1, 0),
    unemployed = ifelse(uemp3m == 1, 1, 0),
    sex = gndr - 1, # sex variable erstellen
    ethnic = ifelse(blgetmg == "1", 1, 0),
    welfare = ifelse(hincsrca %in% c(5,6), 1, 0)
  ) %>%
  mutate(
    id = 1:n(),
    year = case_when(
      essround == 8 ~ "2016",
      essround == 7 ~ "2014",
      essround == 6 ~ "2012",
      essround == 5 ~ "2010",
      essround == 4 ~ "2008",
      essround == 3 ~ "2006",
      essround == 2 ~ "2004",
      essround == 1 ~ "2002",
      TRUE ~ "") %>% 
      as.numeric
    ) %>% 
  mutate(year_2016 = ifelse(year == 2016, 1, 0)) %>% 
  mutate(year_2014 = ifelse(year == 2014, 1, 0)) %>% 
  mutate(year_2012 = ifelse(year == 2012, 1, 0)) %>% 
  mutate(year_2010 = ifelse(year == 2010, 1, 0))

var_checks <- function(vars) {
  list(
    table = table(vars),
    var_label = var_label(vars),
    val_labels = val_labels(vars),
    is.character = is.character(vars),
    is.numeric = is.numeric(vars)
  )
}
# var_checks(ess$mnrgtjb)
# 
# var_checks(mlogit_ess$imm_culture)
# 
# table(mlogit_ess$unemployed)
# 
# mlogit_ess %>% dplyr::select(educ) %>% table()

table(mlogit_ess$year)

ess_year <- mlogit_ess %>% 
  group_by(year, target) %>% 
  tally() %>% 
  na.omit() %>% 
  tidyr::spread("target", "n") %>% 
  ungroup() %>% 
  mutate(total = Establishment + `Progressive Populism` + `Traditionalist Populism`) %>% 
  mutate(Establishment = 100*round(Establishment / total, 4)) %>% 
  mutate(`Progressive Populism` = 100*round(`Progressive Populism` / total, 4)) %>% 
  mutate(`Traditionalist Populism` = 100*round(`Traditionalist Populism` / total, 4)) %>% 
  select(-total) %>% 
  gather(type, value, -year) 

ess_year %>% 
  ggplot(aes(year, value, color = type)) +
  geom_line() +
  geom_point(size = 2) +
  facet_wrap(~type, scales = "free_y", ncol = 1) +
  scale_y_continuous(breaks = seq(0,100, by = 2), 
                     labels = paste0(seq(0,100, by = 2), "%")) +
  ggrepel::geom_text_repel(aes(label = paste0(value, "%")), 
            # vjust = 1.5,
            # hjust = 1,
            color = "black", size = 5) +
  ggthemes::theme_hc() +
  ggthemes::scale_color_fivethirtyeight() +
  xlab("") +
  ylab("Support for Parties in %") #+
  #ggtitle("Support for Establishment/Populist Parties Across Years") +
 # labs(caption = "Source: ESS Data Round 5 - 8; N = 87238") 


ggsave(filename = "text/images/yearplot.png", width = 10, height = 10)
save(ess_year, file = "text/data/ess_year.Rdata")
```

# Regions

```{r}
cntry_dat <- plyr::rbind.fill(
data.frame(stringsAsFactors=FALSE,
          cntry = c("Denmark", "Estonia", "Faroe Islands", "Finland", "Iceland",
                 "Ireland", "Isle of Man", "Latvia", "Lithuania", "Norway",
                 "Svalbard and Jan Mayen Islands", "Sweden",
                 "United Kingdom"),
          regional = "north"),
data.frame(stringsAsFactors=FALSE,
          cntry = c("Albania", "Andorra", "Bosnia and Herzegovina",
                   "Croatia", "Gibraltar", "Greece", "Holy See", "Italy",
                   "Malta", "Montenegro", "Portugal", "San Marino", "Serbia",
                   "Slovenia", "Spain", "Cyprus",
                   "The former Yugoslav Republic of Macedonia"),
          regional = "south"),
data.frame(stringsAsFactors=FALSE,
          cntry = c("Austria", "Belgium", "France", "Germany",
                    "Liechtenstein", "Luxembourg", "Monaco", "Netherlands",
                    "Switzerland"),
          regional = "west"),
data.frame(stringsAsFactors=FALSE,
           cntry = c("Belarus", "Bulgaria", "Czech Republic", "Hungary", "Poland", 
                     "Republic of Moldova", "Romania", "Russian Federation", "Slovakia",
                     "Ukraine"), 
           regional = "east")
)

# https://unstats.un.org/unsd/methodology/m49/

cntry_dat %<>% 
  mutate(cntry = countrycode::countrycode(cntry, "country.name", "country.name")) 

# uk <- mlogit_ess %>%
#   filter(cntry == "United Kingdom") %>%
#   mutate(regional = "north")


mlogit_ess <- left_join(cntry_dat, mlogit_ess, by = "cntry") 

# mlogit_ess <- rbind(mlogit_ess, uk)

mlogit_ess %<>% 
  mutate(north = ifelse(regional == "north", 1, 0)) %>% 
  mutate(south = ifelse(regional == "south", 1, 0)) %>% 
  mutate(east = ifelse(regional == "east", 1, 0)) %>% 
  mutate(west = ifelse(regional == "west", 1, 0)) 

table(mlogit_ess$regional, mlogit_ess$target)

table(mlogit_ess$regional, mlogit_ess$cntry)

regional_ess <- mlogit_ess %>% 
  group_by(regional, target) %>% 
  tally() %>% 
  na.omit() %>% 
  tidyr::spread("target", "n") %>% 
  ungroup() %>% 
  mutate(regional = capitalizeStrings(regional)) %>% 
  mutate(total = Establishment + `Progressive Populism` + `Traditionalist Populism`) %>% 
  mutate(Establishment = 100*round(Establishment / total, 4)) %>% 
  mutate(`Progressive Populism` = 100*round(`Progressive Populism` / total, 4)) %>% 
  mutate(`Traditionalist Populism` = 100*round(`Traditionalist Populism` / total, 4)) %>% 
  select(-total) %>% 
  gather(type, value, -regional) 

regional_ess %>% 
  ggplot(aes(regional, value, fill = type)) +
  geom_bar(stat = "identity", position = "dodge") +
  #coord_flip() +
  geom_text(aes(ymax = 100, label = paste0(value, "%")), 
            vjust = -0.5,
            hjust = 0.5,
            color = "black",
            position = position_dodge(0.9), size = 4) +
  ggthemes::theme_hc() +
  ggthemes::scale_color_fivethirtyeight() + 
  facet_wrap(~type, scale = "fixed") +
  scale_y_continuous(breaks = seq(0,100, by = 25), 
                   labels = paste0(seq(0,100, by = 25),"%")) +
  #scale_x_discrete("", labels = )
  guides(fill = F) +
  xlab("") +
  ylab("Support for Parties in %") #+
 # ggtitle("Support for Establishment/Populist Parties Across European Regions") +
#  labs(caption = "Source: ESS Data Round 5 - 8; N = 87238") 
  
ggsave(filename = "text/images/regionalplot.png", width = 10, height = 6)
save(regional_ess, file = "text/data/regional_ess.Rdata")
```




# Factorscores

```{r}
anti_imm_dat <- mlogit_ess %>%
  select(imm_culture, imm_badecon, imm_worselive) %>%
  mutate_all(as.numeric) 

mlogit_ess <- anti_imm_dat %>%
  psych::fa() %>%
  predict.psych(data = anti_imm_dat) %>%
  as.data.frame() %>%
  transmute(anti_imm = range01(MR1)*10) %>%
  cbind(mlogit_ess)

minus_7 <- function(var) {
  7 - var
}

fa_dat <- mlogit_ess %>%
  select(ipcrtiv, impfree, impdiff, ipadvnt, ipgdtim, impfun,
         impsafe , ipstrgv , ipfrule , ipbhprp , ipmodst , imptrad,
         imprich , iprspot , ipshabt , ipsuces,
         ipeqopt , ipudrst , impenv , iphlppl , iplylfr
         ) %>% 
    mutate_all(as.numeric) %>% 
    mutate_all(minus_7) 


# cronbachs alpha
## openness to change

openness_dat <- fa_dat %>%
  select(ipcrtiv , impfree , impdiff , ipadvnt , ipgdtim , impfun) %>%
  mutate_all(as.numeric) 

fa_dat <- openness_dat %>%
  psych::fa() %>%
  predict.psych(data = openness_dat) %>%
  as.data.frame() %>%
  transmute(openness = (1-range01(MR1))*10) %>%
  cbind(fa_dat)


conservation_dat <- fa_dat %>%
  select(impsafe , ipstrgv , ipfrule , ipbhprp , ipmodst , imptrad) %>%
  mutate_all(as.numeric) 

fa_dat <- conservation_dat %>%
  psych::fa() %>%
  predict.psych(data = conservation_dat) %>%
  as.data.frame() %>%
  transmute(conservation = range01(MR1)*10) %>%
  cbind(fa_dat)


selfenhance_dat <- fa_dat %>%
  select(imprich , iprspot , ipshabt , ipsuces) %>%
  mutate_all(as.numeric) 

fa_dat <- selfenhance_dat %>%
  psych::fa() %>%
  predict.psych(data = selfenhance_dat) %>%
  as.data.frame() %>%
  transmute(selfenhance = (1-range01(MR1))*10) %>%
  cbind(fa_dat)


selftrans_dat <- fa_dat %>%
  select(ipeqopt , ipudrst , impenv , iphlppl , iplylfr) %>%
  mutate_all(as.numeric) 

fa_dat <- selftrans_dat %>%
  psych::fa() %>%
  predict.psych(data = selftrans_dat) %>%
  as.data.frame() %>%
  transmute(selftrans = range01(MR1)*10) %>%
  cbind(fa_dat)



fa_dat <- fa_dat %>% 
  # mutate_all(range01) %>% 
  # mutate(openness = (ipcrtiv + impfree + impdiff + ipadvnt + ipgdtim + impfun)/6) %>% 
  # mutate(conservation = (impsafe + ipstrgv + ipfrule + ipbhprp + ipmodst + imptrad)/6) %>% 
  # mutate(selfenhance = (imprich + iprspot + ipshabt + ipsuces)/4) %>% 
  # mutate(selftrans = (ipeqopt + ipudrst + impenv + iphlppl + iplylfr)/5) %>% 
  # mutate_all(range01) %>% 
  mutate(opendim = (range01((openness - conservation))*10)-5) %>% 
  mutate(selfdim = (range01((selftrans - selfenhance))*10)-5)

hist(fa_dat$opendim)
max(fa_dat$opendim, na.rm=T)
min(fa_dat$opendim, na.rm=T)

mlogit_ess <- fa_dat %>% 
  select(openness, conservation, selfenhance, selftrans, opendim, selfdim) %>% 
  cbind(mlogit_ess) #%>% 
  #na.omit()

global_dat <- mlogit_ess %>%
  select(trust_un, trust_eu) %>%
  mutate_all(as.numeric) 

mlogit_ess <- global_dat %>%
  psych::fa() %>%
  predict.psych(data = global_dat) %>%
  unlist() %>% as.character() %>% as.numeric() %>%
  data.frame(globalism = .) %>%
  transmute(globalism = range01(globalism)*5) %>%
  cbind(mlogit_ess) 

govsat_dat <- mlogit_ess %>%
  select(stfgov, trust_gov, demsat) %>%
  mutate_all(as.numeric) 

mlogit_ess <- govsat_dat %>%
  psych::fa() %>%
  predict.psych(data = govsat_dat) %>%
  unlist() %>% as.character() %>% as.numeric() %>%
  data.frame(govsat = .) %>%
  transmute(govsat = range01(govsat)*5) %>%
  cbind(mlogit_ess) 

mlogit_ess %<>%
#   mutate(anti_imm = range01(
#                     range01(imm_culture) + 
#                     range01(imm_badecon) + 
#                     range01(imm_worselive)
#                     )*10)
  dplyr::select(target, imm_culture, imm_badecon, imm_worselive, anti_imm, econ_unsat, globalism, econ_insec, aut_safe, aut_behave, aut_rules, aut_trad, aut_govstrong, demsat, age, trust_un, trust_eu, trust_gov, govsat, religion, rural, educ, unemployed, sex, ethnic, welfare, lrscale, openness, conservation, selfenhance, selftrans, opendim, selfdim, pweight, regional, east, west, north, south, cntry, year_2016, year_2014, year_2012, year_2010, year) %>% 
  na.omit() %>% 
  mutate_all(labelled::remove_labels)


```


# Boxplots

```{r}
options(scipen = 999)
source("helper_functions.R")
my_comparisons <- list(c("Establishment", "Traditionalist Populism"),
                        c("Establishment", "Progressive Populism"), 
                        c("Progressive Populism", "Traditionalist Populism"))

symnum.args <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1), 
                    symbols = c("p < 0.001", "p < 0.001", "p < 0.01", "p < 0.05", "ns"))

mlogit_ess %>% 
  drop_na(target) %>% 
  group_by(target) %>% 
  summarise(sd_lrscale = sd(lrscale, na.rm = T) %>% 
            round(., 2),
            lrscale = mean(lrscale, na.rm = T) %>% 
            round(., 2)) -> leftright_means


leftright <- mlogit_ess %>%
  drop_na(target) %>% 
  ggplot(aes(target, lrscale, group = target, fill = target)) +
  geom_violin()  + 
  geom_boxplot(width=0.2, fill = "white")  + 
  geom_hline(yintercept = mean(mlogit_ess$lrscale, na.rm = T), linetype = 2) + #line at base mean
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  ggpubr::stat_compare_means(label = "p.format", 
                        comparisons = my_comparisons, 
                             symnum.args = symnum.args) + # Add pairwise comparisons p-value
  ggpubr::stat_compare_means(label.y = 9.3, label.x = 3.4) +    # Add global p-value
  guides(fill=F) +
  xlab("") +
  ylab("Left-Right Scale") +
  ggtitle("Left-Right Scale by Party Support") +
  #labs(caption = "Source: ESS Data Round 5 - 8; N = 87238") +
  coord_flip() +
  geom_text(data = leftright_means, 
            aes(group = target, label = lrscale), nudge_y = 0.5) +
  theme(axis.text=element_text(size = 10), 
        title = element_text(size = 18, face = "bold"), 
        plot.caption = element_text(size = 10),
        axis.title=element_text(size = 10),
        axis.text.y = element_text(face = "bold"))

#ggsave(filename = "images/box_leftright.png", width = 10, height = 6)

mlogit_ess %>% 
  drop_na(target) %>% 
  group_by(target) %>% 
  summarise(sd_age = sd(age, na.rm = T) %>% 
            round(., 2),
            age = mean(age, na.rm = T) %>% 
            round(., 2)) -> age_means

age <- mlogit_ess %>%
  drop_na(target) %>% 
  ggplot(aes(target, age, group = target, fill = target)) +
  geom_violin()  + 
  geom_boxplot(width=0.2, fill = "white")  + 
  geom_hline(yintercept = mean(mlogit_ess$age, na.rm = T), linetype = 2) + #line at base mean
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  ggpubr::stat_compare_means(label = "p.format", 
                        comparisons = my_comparisons, 
                             symnum.args = symnum.args) + # Add pairwise comparisons p-value
  ggpubr::stat_compare_means(label.y = 90.3, label.x = 3.4) +    # Add global p-value
  guides(fill=F) +
  xlab("") +
  ylab("Age in Years") +
  ggtitle("Age by Party Support") +
  #labs(caption = "Source: ESS Data Round 5 - 8; N = 87238") +
  coord_flip() +
  geom_text(data = age_means, 
            aes(group = target, label = age), nudge_y = 8) +
  theme(axis.text=element_text(size = 10), 
        title = element_text(size = 18, face = "bold"), 
        plot.caption = element_text(size = 10),
        axis.title=element_text(size = 10),
        axis.text.y = element_text(face = "bold"))


#ggsave(filename = "images/box_age.png", width = 10, height = 6)

mlogit_ess %>% 
  drop_na(target) %>% 
  group_by(target) %>% 
  summarise(sd_educ = sd(educ, na.rm = T) %>% 
            round(., 2),
            educ = mean(educ, na.rm = T) %>% 
            round(., 2)) -> educ_means

educ <- mlogit_ess  %>%
  drop_na(target) %>% 
  ggplot(aes(target, educ, group = target, fill = target)) +
  geom_violin()  + 
  geom_boxplot(width=0.2, fill = "white")  + 
  geom_hline(yintercept = mean(mlogit_ess$educ, na.rm = T), linetype = 2) + #line at base mean
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  ggpubr::stat_compare_means(label = "p.format", 
                        comparisons = my_comparisons, 
                             symnum.args = symnum.args) + # Add pairwise comparisons p-value
  ggpubr::stat_compare_means(label.y = 6.3, label.x = 3.4) +    # Add global p-value
  guides(fill=F) +
  xlab("") +
  ylab("Education") +
  ggtitle("Education by Party Support") +
  #labs(caption = "Source: ESS Data Round 5 - 8; N = 87238") +
  coord_flip() +
  geom_text(data = educ_means, 
            aes(group = target, label = educ), nudge_y = 0.23) +
  theme(axis.text=element_text(size = 10), 
        title = element_text(size = 18, face = "bold"), 
        plot.caption = element_text(size = 10),
        axis.title=element_text(size = 10),
        axis.text.y = element_text(face = "bold"))


#ggsave(filename = "images/box_education.png", width = 10, height = 6)

mlogit_ess %>% 
  drop_na(target) %>% 
  group_by(target) %>% 
  summarise(sd_religion = sd(religion, na.rm = T) %>% 
            round(., 2),
            religion = mean(religion, na.rm = T) %>% 
            round(., 2)) -> relig_means

pacman::p_load(grDevices)

relig <- mlogit_ess  %>%
  drop_na(target) %>% 
  ggplot(aes(target, religion, group = target, fill = target)) +
  geom_violin()  + 
  geom_boxplot(width=0.2, fill = "white")  + 
  geom_hline(yintercept = mean(mlogit_ess$religion, na.rm = T), linetype = 2) + #line at base mean
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() + 
  ggpubr::stat_compare_means(label = "p.format", 
                        comparisons = my_comparisons, 
                             symnum.args = symnum.args) + # Add pairwise comparisons p-value
  ggpubr::stat_compare_means(label.y = 9.3, label.x = 3.4) +    # Add global p-value
  guides(fill=F) +
  xlab("") +
  ylab("Religiosity") +
  ggtitle("Religiosity by Party Support") +
  #labs(caption = "Source: ESS Data Round 5 - 8; N = 87238") +
  coord_flip() +
  geom_text(data = relig_means, 
            aes(group = target, 
                label = religion), nudge_y = 0.8) +
  theme(axis.text=element_text(size = 10), 
        title = element_text(size = 18, face = "bold"), 
        plot.caption = element_text(size = 10),
        axis.title=element_text(size = 10),
        axis.text.y = element_text(face = "bold"))


#ggsave(filename = "images/box_religiosity.png", width = 10, height = 6)

plot2by2 <- cowplot::plot_grid(leftright, age, educ, relig,
                      labels = c("A", "B", "C", "D"), ncol = 2)

cowplot::save_plot("text/images/plot2by2.png", plot2by2,
          ncol = 2, # we're saving a grid plot of 2 columns
          nrow = 2, # and 2 rows
          base_height = 6,
          base_width = 10,
          # each individual subplot should have an aspect ratio of 1.3
          base_aspect_ratio = 1.3
          )

leftright_means %>% 
  left_join(age_means) %>% 
  left_join(educ_means) %>% 
  left_join(relig_means) %>%  
  mutate(cite_lrscale = paste0("(Mean = ", lrscale, "; SD = ", sd_lrscale, ")")) %>%  
  mutate(cite_age = paste0("(Mean = ", age, "; SD = ", sd_age, ")")) %>%  
  mutate(cite_educ = paste0("(Mean = ", educ, "; SD = ", sd_educ, ")")) %>%  
  mutate(cite_religion = paste0("(Mean = ", religion, "; SD = ", sd_religion, ")")) %>% 
  gather(key, value, -target)  %>% 
  mutate(target = case_when(
    str_detect(target,"ressive") ~ "prog", 
    str_detect(target,"radition") ~ "trad",
    TRUE ~ "est")) -> boxplot_dat

save(boxplot_dat, file = "text/data/boxplot_dat.Rdata")


```


# Mlogit

```{r}
library(nnet)
mlogit_ess$populism2 <- relevel(mlogit_ess$target, ref = "Establishment")

test <- multinom(
  populism2 ~
    # economic deprivation
    econ_insec + unemployed + welfare +
    # cultural backlash
    anti_imm + openness + conservation + selfenhance + selftrans + globalism + govsat +
    # control variables
    age + educ + sex + lrscale + ethnic + religion + rural + east + north + south +
    year_2016 + year_2014 + year_2012,
    #data
    data = mlogit_ess, weights = pweight)

# screenreg(test)
# stargazer::stargazer(test, type = "text")

multi1.rrr <- exp(coef(test))

stargazer::stargazer(test, type = "text",coef=list(multi1.rrr), p.auto=FALSE)

summary(test)

#car::Anova(test)

PseudoR2(test)

regm2 <- step(test)
# 
# GGally::ggcoef(regm2, exponentiate = TRUE) + facet_grid(~y.level)

tidy(regm2, exponentiate = T, conf.int = TRUE) %>% 
  # filter(term != "south") %>% 
  # filter(term != "east") %>% 
  # filter(term != "north") %>% 
  # filter(term != "(Intercept)") %>% 
  ggplot() + aes(x = term, y = estimate, 
                 ymin = conf.low, 
                 ymax = conf.high, color = y.level) + 
  geom_hline(yintercept = 1, 
             color = "gray25", 
             linetype = "dotted") + 
  geom_errorbar(position = position_dodge(0.5), width = 0) + 
  geom_point(position = position_dodge(width = 0.5)) + scale_y_log10() + 
  coord_flip()

```


# Sequentalism

```{r}
get_p_values <- function (pval) {
  dplyr::case_when(is.na(pval) ~ "", pval < 0.001 ~ "***", 
    pval < 0.01 ~ "**", pval < 0.05 ~ "*", TRUE ~ "")
}

prep_dat <- function(model, modelname) {
  tidy_model <- step(model) %>% 
  tidy(exponentiate = T, conf.int = TRUE) %>% 
  mutate(model = modelname) %>% 
  mutate(stars = get_p_values(p.value)) 
  
tidy_model$mcfadden <- round(PseudoR2(model), 2)
  
  return(tidy_model)
}




library(nnet)
mlogit_ess$populism2 <- relevel(mlogit_ess$target, ref = "Establishment")

controls <- multinom(
  populism2 ~
    # economic deprivation
    #econ_unsat + econ_insec + unemployed + welfare +
    # cultural backlash
    #anti_imm + openness + conservation + selfenhance + selftrans + globalism + govsat +
    # control variables
    age + educ + sex + lrscale + ethnic + religion + rural + east + north + south +
    year_2016 + year_2014 + year_2012,
    #data
    data = mlogit_ess, weights = pweight)

# controls_tidy <- step(controls) %>% 
#   tidy(exponentiate = T, conf.int = TRUE) %>% 
#   mutate(model = "control") %>% 
#   mutate(stars = get_p_values(p.value)) %>% 
#   mutate(mcfadden = round(PseudoR2(controls), 2)) 

  # cowplot::add_sub(gg_coefs, 
  #                  label = paste(expression(paste("McFadden's Pseudo R^2:")), 
  #                                           gg_coefs$mcfadden), 
  #                  x = 0, hjust = 0) %>%
  # cowplot::ggdraw()

fit1 <- multinom(
  populism2 ~
    # control variables
    age + educ + sex + lrscale + ethnic + religion + rural + east + north + south +
    year_2016 + year_2014 + year_2012 +
    # economic deprivation
    econ_insec + unemployed + welfare,
    # cultural backlash
    #anti_imm + openness + conservation + selfenhance + selftrans + globalism + govsat +
    #data
    data = mlogit_ess, weights = pweight)

# fit1_tidy <- step(fit1) %>% 
#   tidy(exponentiate = T, conf.int = TRUE) %>% 
#   mutate(model = "control") %>% 
#   mutate(stars = get_p_values(p.value)) %>% 
#   mutate(mcfadden = round(PseudoR2(fit1), 2)) 


fit2 <- multinom(
  populism2 ~
    # control variables
    age + educ + sex + lrscale + ethnic + religion + rural + east + north + south +
    year_2016 + year_2014 + year_2012 +
    # economic deprivation
    #econ_unsat + econ_insec + unemployed + welfare +
    # cultural backlash
    anti_imm + openness + conservation + selfenhance + selftrans + globalism + govsat,
    #data
    data = mlogit_ess, weights = pweight)


fit3 <- multinom(
  populism2 ~
    # control variables
    age + educ + sex + lrscale + ethnic + religion + rural + east + north + south +
    year_2016 + year_2014 + year_2012 +
    # economic deprivation
    econ_insec + unemployed + welfare +
    # cultural backlash
    anti_imm + openness + conservation + selfenhance + selftrans + globalism + govsat ,
    #data
    data = mlogit_ess, weights = pweight)

fit4 <- multinom(
  populism2 ~
    # control variables
    age + educ + sex + lrscale + ethnic + religion + rural + east + north + south +
    year_2016 + year_2014 + year_2012 +
    # economic deprivation
    econ_insec + unemployed + welfare +
    # cultural backlash
    anti_imm + openness + conservation + selfenhance + selftrans + globalism + govsat +
    # interactions
    unemployed * anti_imm + econ_insec * conservation + welfare * selfenhance,
    #data
    data = mlogit_ess, weights = pweight)

# PseudoR2(controls)
# PseudoR2(fit1)
# PseudoR2(fit2)
# PseudoR2(fit3)
# PseudoR2(fit4)
# 

anovies <- c("-", paste0(
round(c(anova(controls, fit1)$`LR stat.`[2],
anova(fit1, fit2)$`LR stat.`[2],
anova(fit2, fit3)$`LR stat.`[2],
anova(fit3, fit4)$`LR stat.`[2]), 2),

c(anova(controls, fit1)$`Pr(Chi)`[2],
anova(fit1, fit2)$`Pr(Chi)`[2],
anova(fit2, fit3)$`Pr(Chi)`[2],
anova(fit3, fit4)$`Pr(Chi)`[2]) %>% 
  get_p_values()
))



# # screenreg(test)
#  stargazer::stargazer(controls, fit1, fit2, fit3, type = "html", apply.coef = exp, p.auto=FALSE)

all_mods <- rbind( 
prep_dat(controls, "control"),
prep_dat(fit1, "model1"),
prep_dat(fit2, "model2"),
prep_dat(fit3, "model3"),
prep_dat(fit4, "model4")
) 

mcfaddies <- all_mods %>% 
  group_by(model, mcfadden) %>% 
  tally() %>%
  .$mcfadden

unique(all_mods$term)


control_variables <- c("age", "educ", "sex", "lrscale", "ethnic", 
  "religion", "rural", "south", "east", "north")
  
economic <- c("econ_insec", "unemployed", "welfare")

cultural <- c("anti_imm", "openness", 
             "conservation", "selfenhance", "selftrans", 
             "globalism", "govsat")

all_mods %>% 
  filter(term != "south") %>% 
  filter(term != "east") %>% 
  filter(term != "north") %>% 
  filter(term != "year_2016") %>% 
  filter(term != "year_2014") %>% 
  filter(term != "year_2012") %>% 
  filter(term != "(Intercept)") %>% 
  mutate(variable_groups = case_when(
    term %in% control_variables ~ "Controls",
    term %in% economic ~ "Economic",
    term %in% cultural ~ "Cultural",
    TRUE ~ "Interactions"
  )) %>% 
  mutate(term = fct_relevel(term, 
                            levels = c("unemployed:anti_imm", "govsat", "globalism",                                  
                                       "selftrans", "selfenhance", "conservation", 
                        "openness", "anti_imm", "welfare", "unemployed", "econ_insec",
                        "rural", "religion", "ethnic", "lrscale", "sex", 
                        "educ", "age", "unemployed:anti_imm",
                        "econ_insec:conservation"))) %>% 
  ggplot() + aes(x = term, y = estimate, 
                 ymin = conf.low, 
                 ymax = conf.high, 
                 color = y.level) + 
  geom_hline(yintercept = 1, 
             color = "gray25", 
             linetype = "dotted") + 
  geom_errorbar(position = position_dodge(0.5), width = 0) + 
  geom_point(aes(shape = variable_groups), 
             position = position_dodge(width = 0.5)) + 
  scale_y_log10() +
  geom_vline(xintercept = seq(1.5, length(unique(all_mods$term)) - 0.5, 1), 
             lwd = 1, colour = "grey", alpha = 0.7) +
  geom_text(aes(x = term, 
                y = estimate + 0.01,
                label = paste(sprintf('%.2f', estimate, 2), stars)), 
                position = position_dodge(1.2)) +
  coord_flip() +
  scale_y_continuous(breaks = seq(-2,2, by = 0.3)) +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_fivethirtyeight() +
  cowplot::background_grid(major = 'y', minor = "none") + # add thin horizontal lines
  cowplot::panel_border() +# and a border around each panel
  xlab("") +
  ylab("Odds Ratios") + 
  # labs(caption = paste(expression("McFadden's Pseudo R^2:")), 
  #                                          gg_coefs$mcfadden) +
  facet_grid(~ model, scales = "fixed") +
  annotate("label", x = -1, y = 1, label = paste("McFadden's R2.:",
                                                  mcfaddies,
                                                  "\n N:", rep(nrow(mlogit_ess), 5),
                                                  "\n LRT:", anovies)) +
  # annotate("label", x = 7.5, y = 0.7, label = "Controls") +
  # annotate("label", x = 11.5, y = 0.7, label = "Economic") +
  # annotate("label", x = 18.5, y = 0.7, label = "Cultural") +
  # annotate("label", x = 19.5, y = 0.7, label = "Interactions") +
  # expand_limits(x = 21) + 
  geom_text(aes(x = -2, label = "")) +
  scale_x_discrete(limits = c("unemployed:anti_imm",
                              "Interactions",
                              "anti_imm", "openness", 
                              "conservation", "selfenhance", "selftrans", 
                              "globalism", "govsat",
                              "Culture",
                              "econ_insec", "unemployed", 
                              "welfare",
                              "Economics",
                              "age", "educ", "sex", "lrscale", 
                              "ethnic", "religion", "rural",
                              "Controls"), 
                   labels = c("Controls"=expression(displaystyle(bold(Controls))), 
                            "Economics"=expression(displaystyle(bold(Economics))),
                            "Culture"=expression(displaystyle(bold(Culture))), 
                            "Interactions"=expression(displaystyle(bold(Interactions))), 
                            parse=TRUE))

ggsave(filename = "images/onebigmotherfucker.png", width = 15, height = 10)
 
# multi1.rrr <- exp(coef(test))
# 
# stargazer::stargazer(test, type="text",coef=list(multi1.rrr), p.auto=FALSE)

# TODO Make a map (or two)
# TODO Make stuff citeable
# TODO Decide which interactions
# TODO Make probability plots

unique(all_mods$term)
```
# Citation Stuff

```{r}

cite_dat <- data.frame(anovies = anovies, model = unique(all_mods$model)) %>% 
  right_join(all_mods)

cite_dat %>% 
  filter(model == "control") %>% 
  mutate(id = 1:n()) %>% 
  select(y.level, term, estimate) %>% 
  spread("term", "estimate")

get_p_cite <- function (pval) {
  dplyr::case_when(is.na(pval) ~ "", 
                   pval < 0.001 ~ "< 0.001",
                   pval < 0.01 ~ "< 0.01", 
                   pval < 0.05 ~ "< 0.05", 
                   pval >= 0.05 ~ paste0("= ", sprintf('%.2f', pval)), 
                   TRUE ~ "")
}

cite_dat %<>% 
  mutate(estimate = sprintf('%.2f', estimate)) %>% 
  mutate(conf.low = sprintf('%.2f', conf.low)) %>% 
  mutate(conf.high = sprintf('%.2f', conf.high)) %>% 
  mutate(citation = paste0("OR = ", 
                          estimate, "; ",
                          "95% CI ", "(", conf.low, " - ", 
                          conf.high, "); ", 
                          "p ", get_p_cite(p.value))) %>% 
  mutate(y.level = ifelse(y.level == "Progressive Populism", "prog", "trad"))

cite_complete <- function(mod, parameter, populism) {
  cite_dat %>%
    filter(model == mod) %>% 
    filter(term == parameter) %>% 
    filter(y.level == populism) %>% 
    select(citation) %>% .$citation
}

cite_OR <- function(mod, parameter, populism) {
  cite_dat %>%
    filter(model == mod) %>% 
    filter(term == parameter) %>% 
    filter(y.level == populism) %>% 
    select(estimate) %>% .$estimate 
}

cite_complete(mod = "control", 
              parameter = "age", 
              populism = "prog")

cite_OR(mod = "control", 
              parameter = "age", 
              populism = "prog")


save(cite_dat, file = "data/cite_dat.Rdata")
```


## Plot Predictions - Singular

```{r}
test <- multinom(
  populism2 ~
    # economic deprivation
    econ_unsat + econ_insec + unemployed +
    # cultural backlash
    anti_imm + openness + conservation + selfenhance + selftrans + globalism + govsat +
    # control variables
    age + educ + sex + lrscale + ethnic + religion + rural + east + north + south,
    #data
    data = mlogit_ess, weights = pweight)


screenreg(test)

## Automatic Picking of Scales
#from_to <- as.vector(names(table(ess_mlogit$openness)))
#fit.eff <- effects::effect("openness", 
#                           test, 
#                           xlevels = list(openness = from_to))
## or
#fit.eff <- effects::effect("openness", 
#                           test)
## or put them in by hand
fit.eff <- effects::effect("anti_imm", 
                           fit4, 
                           xlevels = list(anti_imm = c(1:10)))

data.frame(fit.eff$model.matrix, 
           fit.eff$prob, 
           fit.eff$lower.prob, 
           fit.eff$upper.prob) %>% 
  select(anti_imm, prob.Traditionalist.Populism, prob.Establishment,
         prob.Progressive.Populism, L.prob.Establishment, 
         U.prob.Establishment, L.prob.Traditionalist.Populism, 
         U.prob.Traditionalist.Populism, L.prob.Progressive.Populism, 
         U.prob.Progressive.Populism, -X.Intercept.) %>% 
  gather(key = variable, value = value, -anti_imm, 
           -L.prob.Establishment, -U.prob.Establishment,
           -L.prob.Traditionalist.Populism, -U.prob.Traditionalist.Populism,
         -L.prob.Progressive.Populism, -U.prob.Progressive.Populism) %>% 
  mutate(type = case_when(
    str_detect(variable, "Traditionalist") ~ "Tradionalist Populism",
    str_detect(variable, "Progressive") ~ "Progressive Populism",
    str_detect(variable, "Establishment") ~ "Establishment"
  )) %>%
    mutate(lower = case_when(
    type == "Establishment" ~ L.prob.Establishment*100,
    type == "Progressive Populism" ~ L.prob.Progressive.Populism*100,
    type == "Tradionalist Populism" ~ L.prob.Traditionalist.Populism*100
  )) %>% 
    mutate(upper = case_when(
    type == "Establishment" ~ U.prob.Establishment*100,
    type == "Progressive Populism" ~ U.prob.Progressive.Populism*100,
    type == "Tradionalist Populism" ~ U.prob.Traditionalist.Populism*100
  )) %>% 
  mutate(value = value * 100) %>% 
  ggplot(aes(anti_imm, value, colour = type)) +
    geom_smooth(method = "loess", 
               #formula = y ~ s(x, k = 1), 
               size = 1.2, se = F) +
    geom_ribbon(aes(ymin = lower, ymax = upper), 
               fill = "gray70", alpha = 0.5, colour=NA) +
 #  geom_jitter(alpha = 0.01) +
  labs(y = "Marginal Probability") +
    ggthemes::theme_hc() +
    ggthemes::scale_color_fivethirtyeight() + 
    facet_wrap(~type, scales = "free") +
    scale_y_continuous(breaks = seq(0,100, by = 2.5), 
                     labels = paste0(seq(0,100, by = 2.5),"%"))
```

## Plot Predictions - Interactions

```{r}
test <- multinom(
  populism2 ~
    # economic deprivation
    econ_unsat + econ_insec + unemployed +
    # cultural backlash
    anti_imm + openness + conservation + selfenhance + selftrans + globalism + govsat +
    # control variables
    age + educ + sex + lrscale + ethnic + religion + rural + east + north + south +
    # interactions
    anti_imm*unemployed , 
    #data
    data = mlogit_ess, weights = pweight)

screenreg(test)

from_to <- as.vector(names(table(mlogit_ess$anti_imm)))
#table(mlogit_ess$govsat)
# fit.eff <- effects::effect("anti_imm*south", test, xlevels = list(govsat = from_to))

fit.eff <- effects::Effect(c("anti_imm", "unemployed"), 
                           fit4, 
                           xlevels = list(anti_imm = from_to, 
                                          unemployed = c(0, 1)))


data.frame(fit.eff$model.matrix, 
           fit.eff$prob, 
           fit.eff$lower.prob, 
           fit.eff$upper.prob) %>% 
  select(anti_imm, unemployed, # interaction effects
         prob.Traditionalist.Populism, prob.Establishment,
         prob.Progressive.Populism, L.prob.Establishment, 
         U.prob.Establishment, L.prob.Traditionalist.Populism, 
         U.prob.Traditionalist.Populism, L.prob.Progressive.Populism, 
         U.prob.Progressive.Populism, -X.Intercept.) %>% 
  gather(key = variable, value = value, 
         -anti_imm, -unemployed, # interaction effects 
           -L.prob.Establishment, -U.prob.Establishment,
           -L.prob.Traditionalist.Populism, -U.prob.Traditionalist.Populism,
         -L.prob.Progressive.Populism, -U.prob.Progressive.Populism) %>% 
  mutate(type = case_when(
    str_detect(variable, "Traditionalist") ~ "Tradionalist Populism",
    str_detect(variable, "Progressive") ~ "Progressive Populism",
    str_detect(variable, "Establishment") ~ "Establishment"
  )) %>% 
    mutate(lower = case_when(
    type == "Establishment" ~ L.prob.Establishment*100,
    type == "Progressive Populism" ~ L.prob.Progressive.Populism*100,
    type == "Tradionalist Populism" ~ L.prob.Traditionalist.Populism*100
  )) %>% 
    mutate(upper = case_when(
    type == "Establishment" ~ U.prob.Establishment*100,
    type == "Progressive Populism" ~ U.prob.Progressive.Populism*100,
    type == "Tradionalist Populism" ~ U.prob.Traditionalist.Populism*100
  )) %>% 
  mutate(value = value * 100) %>% 
  mutate(Unemployed = as.factor(unemployed)) %>% 
  # mutate(unemployed = as.factor(case_when( 
  #   unemployed == max(unemployed) ~ max(unemployed),
  #   unemployed == min(unemployed) ~ min(unemployed),  
  #   TRUE ~ NA_real_
  # ))) %>% 
  #drop_na(unemployed) %>% 
  ggplot(aes(anti_imm, value, group = Unemployed, colour = Unemployed)) +
    geom_smooth(method = "loess", 
               #formula = y ~ s(x, k = 1), 
               size = 1.2, se = F) +
    geom_ribbon(aes(ymin = lower, ymax = upper), 
               fill = "gray70", alpha = 0.5, colour=NA) +
    scale_colour_manual("", values = c("blue", "red")) +
 #  geom_jitter(alpha = 0.01) +
    labs(y = "Marginal Probability") +
    ggthemes::theme_hc() +
    ggthemes::scale_color_fivethirtyeight() + 
    facet_wrap(~type, scales = "free") +
    scale_y_continuous(breaks = seq(0,100, by = 5), 
                     labels = paste0(seq(0,100, by = 5),"%")) +
  xlab("Anti-Immigration Sentiment") +
  ggtitle("Probabilities of Support for Establishment/Populist Parties") +
  labs(subtitle = "Based on Multinomial Logistic Regression",
       caption = "Source: ESS Data Round 5 - 8") +
  theme(axis.text = element_text(size = 10),
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 10), 
        legend.title = element_text(size = 10), 
        title = element_text(size = 12))


# ggsave(file = here::here("images", "interaction_abstract.png"), 
#        height = 5, width = 8)
```


## Appropriateness

```{r}
head(pp <- fitted(test))
#head(pp <- predict(test, newdata = mlogit_ess, type = "class"))

conf.beta <- confint(object = test , level = 0.95)
conf.beta # Results are in a 3D array

table(pp, mlogit_ess$populism2)

broom::tidy(test)

probs <- pp %>% 
  as_tibble() %>% 
  cbind(mlogit_ess) %>%
  as.data.frame()


 table(mlogit_ess$cntry)

probs %<>% 
  mutate(estab = ifelse(populism2 == "Establishment", T, F)) %>% 
  mutate(lib = ifelse(populism2 == "Progressive Populism", T, F)) %>% 
  mutate(illib = ifelse(populism2 == "Traditionalist Populism", T, F)) 

table(probs$`Traditionalist Populism`>probs$`Progressive Populism` & probs$`Traditionalist Populism`>probs$Establishment, probs$illib)
table(probs$`Progressive Populism`>probs$`Traditionalist Populism` & probs$`Progressive Populism`>probs$Establishment, probs$lib)
table(probs$Establishment>probs$`Progressive Populism` & probs$Establishment>probs$`Traditionalist Populism`, probs$estab)
table(probs$populism2)

checkers <- probs %>% 
  filter(populism2 != "Establishment")

table(checkers$`Traditionalist Populism`>checkers$`Progressive Populism`, checkers$illib)
table(checkers$`Progressive Populism`>checkers$`Traditionalist Populism`, checkers$lib)
table(probs$populism2)
```


## Predictions

```{r}


plot_probs <- function(probs = probs, variable = probs$anti_imm) {
  ss <- probs %>% 
  mutate(variable = as.numeric(variable)) %>% 
  select(variable, `Traditionalist Populism`, `Progressive Populism`, Establishment) %>% 
#  mutate(id = n()) %>% 
  gather(key = variable, value = value)  

names(ss) <- c("variable", "type", "value")

ss %>% 
  mutate(value = value * 100) %>% 
   ggplot(aes(variable, value, colour = type)) +
   geom_smooth(method = "gam", 
               formula = y ~ s(x, k = 1), 
               size = 1.2) +
 #  geom_ribbon(aes(ymin = LO, ymax = HI), fill = "gray70", alpha = 0.5) +
 #  geom_jitter(alpha = 0.01) +
  labs(x = str_glue("{names(ss)[1]}"), y = "Marginal Probability") +
  ggthemes::theme_hc() +
  ggthemes::scale_color_fivethirtyeight() + 
  facet_wrap(~type, scales = "free") +
  scale_y_continuous(breaks = seq(0,100, by = 5), 
                     labels = paste0(seq(0,100, by = 5),"%"))
}

plot_ints <- function(probs, variable = NULL, 
                      variable2 = NULL, type = "minmax", legend_title = "variable") {
#  if (type == "minmax") {

#}
  
ss <- probs %>% 
  mutate(variable = as.numeric(variable)) %>% 
  mutate(variable2 = as.numeric(variable2)) %>% 
  select(variable, variable2, `Traditionalist Populism`, 
         `Progressive Populism`, Establishment) %>% 
    mutate(variable2 = case_when(
    variable2 == max(variable2) ~ max(variable2),
    variable2 == min(variable2) ~ min(variable2),  
    TRUE ~ NA_real_
  )) %>% 
  drop_na(variable2) %>% 
#  mutate(id = n()) %>% 
  gather(key = "type", value = "value", -variable, -variable2) %>% 
  mutate(value = value * 100) 



# if (type == "sd") {
#   ss <- probs %>% 
#     mutate(variable2 = case_when(
#     variable2 == mean(variable2, na.rm = T) + 2*sd(variable2) max(variable2) ~ max(variable2),
#     variable2 == min(variable2) ~ min(variable2),  
#     TRUE ~ NA_real_
#   )) %>% 
#   drop_na(variable2) 
# }

ss %>% 
   ggplot(aes(variable, value, 
              colour = as.factor(variable2), group = variable2)) +
   geom_smooth(method = "gam", 
               formula = y ~ s(x, k = 1), 
               size = 1.2) +
 #  geom_jitter(alpha = 0.01) +
  labs(x = str_glue("{names(ss)[1]}"), y = "Marginal Probability") +
  ggthemes::theme_hc() +
#  scale_colour_hue("", l = 70, c = 150, h = c(90, 20)) + 
  scale_colour_manual(legend_title, values = c("blue", "red")) +
  facet_wrap(~type, scales = "free") +
  scale_y_continuous(breaks = seq(0,100, by = 5), 
                     labels = paste0(seq(0,100, by = 5),"%"))
}

plot_probs(probs, probs$religion)

ggsave(filename = "images/probabs.png", height = 5, width = 12)
# 
# variable <- mlogit_ess$econ_unsat
# variable2 <- mlogit_ess$anti_imm




plot_ints(probs, probs$anti_imm, probs$unemployed)

plot_ints(probs, probs$anti_imm, probs$unemployed, legend_title = "Unemployed over 3 Months") +
  xlab("Anti-Immigration Sentiment")

ggsave(filename = "images/interaction1.png", height = 5, width = 12)


plot_ints(probs, probs$anti_imm, probs$econ_insec, legend_title = "Economic Insecurity") +
  xlab("Anti-Immigration Sentiment")

ggsave(filename = "images/interaction2.png", height = 5, width = 12)


```

# Logistic Regression

```{r}
mlogit_ess %<>% 
  mutate(progressive_populism = ifelse(target == "Progressive Populism", 1, 0)) %>% 
  mutate(trad_populism = ifelse(target == "Traditionalist Populism", 1, 0))   

glmfit <- glm(progressive_populism ~ 
    # economic deprivation
    econ_unsat + econ_insec + unemployed +
    # cultural backlash
    anti_imm + authoritarianism + globalism +
    # control variables
    demsat + trust_gov + govsat + age + educ +  + sex ,
    #data
    data = mlogit_ess, weights = pweight, family = "binomial")

plot_model(glmfit)
screenreg(glmfit)
stargazer(glmfit, type = "text")


nagelkerke(glmfit)

plot_model(glmfit, type = "pred", terms = c("econ_unsat", "unemployed"))

predict(glmfit, mlogit_ess, type = "response") %>% 
  data.frame(predict_prog = .) %>% 
  transmute(predict_prog = predict_prog>=0.5) %>% 
  cbind(mlogit_ess) %>% 
  select(predict_prog, progressive_populism) %>% 
  table()

# Use your model to make predictions, in this example newdata = training set, but replace with your test set    
pdata <- predict(glmfit, newdata = mlogit_ess, type = "response")

# use caret and compute a confusion matrix
confusionMatrix(data = as.numeric(pdata>0.5), reference = mlogit_ess$progressive_populism)

glmfit <- glm(trad_populism ~ 
    # economic deprivation
    econ_unsat + econ_insec + unemployed +
    # cultural backlash
    anti_imm + authoritarianism + globalism +
    # control variables
    demsat + trust_gov + govsat + age + educ +  + sex ,
    #data
    data = mlogit_ess, weights = pweight, family = "binomial")

predict(glmfit, mlogit_ess, type = "response") %>% 
  data.frame(predict_trad = .) %>% 
  transmute(predict_trad = predict_trad>=0.5) %>% 
  cbind(mlogit_ess) %>% 
  select(predict_trad, trad_populism) %>% 
  table()

plot_model(glmfit)
screenreg(glmfit)

plot_model(glmfit, type = "pred", terms = c("econ_unsat"))
```




# Crap


## Human Values

```{r}
# selected <- binoculaR::binoculaR(ess)
# 
# 
# fa_dat <- ess %>%
#   select(selected$var_codes)

#save(fa_dat, file = "data/fa_dat.Rdata")


# openness_dat <- fa_dat %>% 
#   select(ipcrtiv, impfree, impdiff, ipadvnt, ipgdtim, impfun) %>% 
#   psych::pca(1) 
#   #psych::alpha()
# 
# openness_dat %>% 
#   predict(., data = fa_dat)

# pacman::p_install_gh("yrosseel/lavaan")
# 
# fa_model <- 'openness =~ ipcrtiv + impfree + impdiff + ipadvnt + ipgdtim + impfun
#              ipgdtim ~~ impfun
#              ipcrtiv ~~ impfree
#              ipcrtiv ~~ impdiff
#              impfree ~~ ipadvnt'
# 
# 
# fit <- cfa(fa_model, data=fa_dat, 
#                    estimator= "MLM")
# 
# summary(fit, standardized=TRUE, 
#         fit.measures = TRUE, rsq = T)
# 
# openness <- lavaan::lavPredict(fit, newdata = fa_dat, fsm = T)
# 
# #Modifikationsindizes
# modheit <- modificationindices(fit, sort=T, minimum.value = 5)
# modheit
```

## crap 2

```{r}

library(rstan)

p <- predict(test)
table(p)
z <- summary(test)$coefficients/summary(test)$standard.errors
z

# 2-tailed z test
p <- (1 - pnorm(abs(z), 0, 1)) * 2
p

## extract the coefficients from the model and exponentiate
exp(coef(test))

head(pp <- fitted(test))

library(mlogit)
m <- mlogit(populism2 ~ imm_culture, data = mlogit_ess)
# compute a data.frame containing the mean value of the covariates in the sample
z <- with(mlogit_ess, data.frame(price = tapply(price, index(m)$alt, mean), 
	catch = tapply(catch, index(m)$alt, mean), 
econ_insec = mean(econ_insec)))
# compute the marginal effects (the second one is an elasticity
effects(m, covariate = "econ_insec", data = z)
effects(m, covariate = "price", type = "rr", data = z)
effects(m, covariate = "catch", type = "ar", data = z)

library(mnlogit)
#data(Fish, package = "mnlogit")
fm <- formula(populism2 ~ imm_culture )
fit <- mnlogit(fm, mlogit_ess, choiceVar="Establishment", ncores = 2)

### With improper prior it takes about 12 minutes, with about 40% CPU utilization and fans running,
### so you probably don't want to casually run the next line...

system.time (b1 <- brm (populism ~ imm_culture, 
                        data=mlogit_ess,
                        family="categorical", 
                        n.chains=3, 
                        n.iter=3000, 
                        n.warmup=600))
```



## Descriptives

```{r}

# pacman::p_install_gh("systats/binoculaR")
# 
# binoculaR::binoculaR(ess)

# ess %>% 
#   select(prtvede1, prtvede2) %>% na.omit() %>% mutate_all(sjmisc::to_label)

#var_label(ess$imueclt)

#ir <- data.frame (scale (iris[, -5]), Species=iris[, 5])


```


## Applying a different approach

```{r}

#install.packages("mlogit")    
# This is my favorite package to do multinomial logit in R

options(scipen=9)    # To fix notation
# library(MASS)
library(xtable)
library(mlogit)
library(reshape2)    # We will need this package at the very end


mnl.1 <- mlogit(populism2 ~ 1 |
    # economic deprivation
    econ_unsat + econ_insec + unemployed +
    # cultural backlash
    anti_imm + authoritarianism + globalism +
    # control variables
    demsat + trust_gov + govsat + age + educ + sex + lrscale + ethnic + religion + rural,
                data = mlogit_ess, shape = "wide", reflevel = "Establishment", weights = pweight)
summary(mnl.1)

betas <- coef(mnl.1)
varcov <- vcov(mnl.1)
# se <- sqrt(diag(mnl.1))

# betas[1]
# 
# # broom::tidy(mnl.1)
# stargazer(mnl.1, type = "text")

#Let’s set up the simulation.

set.seed(461982)
n <- 1000
sim.pred <- MASS::mvrnorm(n, betas, varcov)


#Extract the variable names.
c.n.2 <- names(betas)[names(betas) %>% str_detect("Traditionalist Populism")]
c.n.3 <- names(betas)[names(betas) %>% str_detect("Progressive Populism")]


#Set the independent variables to some meaningful values storing them into an object.

means <- c(mean(mlogit_ess$econ_unsat, na.rm = T), 
           mean(mlogit_ess$econ_insec, na.rm = T), 
           1, # Employed
           mean(mlogit_ess$anti_imm, na.rm = T),
           mean(mlogit_ess$authoritarianism, na.rm = T), 
           mean(mlogit_ess$globalism, na.rm = T), 
           mean(mlogit_ess$demsat, na.rm = T), 
           mean(mlogit_ess$trust_gov, na.rm = T),
           mean(mlogit_ess$govsat, na.rm = T), 
           mean(mlogit_ess$age, na.rm = T), 
           mean(mlogit_ess$educ, na.rm = T),
           1, #sex
           mean(mlogit_ess$lrscale, na.rm = T),
           1, #ethnic
           mean(mlogit_ess$religion, na.rm = T), 
           mean(mlogit_ess$rural, na.rm = T))

means <- data.frame(econ_unsat = mean(mlogit_ess$econ_unsat, na.rm = T), 
           econ_insec = mean(mlogit_ess$econ_insec, na.rm = T), 
           unemployed = 1, # Employed
#           anti_imm = mean(mlogit_ess$anti_imm, na.rm = T),
           authoritarianism = mean(mlogit_ess$authoritarianism, na.rm = T), 
           globalism = mean(mlogit_ess$globalism, na.rm = T), 
           demsat = mean(mlogit_ess$demsat, na.rm = T), 
           trust_gov = mean(mlogit_ess$trust_gov, na.rm = T),
           govsat = mean(mlogit_ess$govsat, na.rm = T), 
           age = mean(mlogit_ess$age, na.rm = T), 
           educ = mean(mlogit_ess$educ, na.rm = T),
           sex = 1,
           lrscale = mean(mlogit_ess$lrscale, na.rm = T),
           ethnic = 1,
           religion = mean(mlogit_ess$religion, na.rm = T), 
           rural = mean(mlogit_ess$rural, na.rm = T))
)
           
x.range <- seq(min(mlogit_ess$anti_imm, na.rm = T), max(mlogit_ess$anti_imm, na.rm = T), along.with = min(mlogit_ess$anti_imm, na.rm = T):max(mlogit_ess$anti_imm, na.rm = T))

#Create empty matrices for the predictions.
res.1 <- matrix(NA, nrow = length(x.range), ncol = 4)
res.2 <- matrix(NA, nrow = length(x.range), ncol = 4)
res.3 <- matrix(NA, nrow = length(x.range), ncol = 4)

#Run the loop.
i = 2
for(i in 1:length(x.range)){
  a <- x.range[i]
  # Generate vectors of predictions on the linear predictor
  b.2 <- sim.pred[, c.n.2]%*%c(1, means,a)
  b.3 <- sim.pred[, c.n.3]%*%c(1, means,a)
  # Generate vectors of probabilities (notice that category 1 is the baseline)
  p.1 <- 1/(1 + exp(b.2) + exp(b.3))
  p.2 <- exp(b.2)/(1 + exp(b.2) + exp(b.3))
  p.3 <- exp(b.3)/(1 + exp(b.2) + exp(b.3))
  # Put means and CIs in 4 matrices
  res.1[i, ] <- c(a,
                  mean(p.1), 
                  quantile(p.1, p = 0.025),
                  quantile(p.1, p = 0.975))
  res.2[i, ] <- c(a,
                  mean(p.2), 
                  quantile(p.2, p = 0.025),
                  quantile(p.2, p = 0.975))
  res.3[i, ] <- c(a,
                  mean(p.3), 
                  quantile(p.3, p = 0.025),
                  quantile(p.3, p = 0.975))
}

data.sim <- data.frame(rbind(res.1, res.2, res.3))
names(data.sim) <- c("X", "Y", "LO", "HI")
data.sim$GR <- rep(c("Establishment", "Traditional Populism", "Progressive Populism"), each = length(x.range))


install.packages("VGAM")
VGAM::margeff(test)


ggplot(data.sim, aes(x = X, y = Y, group = GR)) +
  geom_line() +
  geom_ribbon(aes(ymin = LO, ymax = HI), fill = "gray70", alpha = 0.5) +
  facet_wrap(~ GR, ncol = 3) +
  scale_y_continuous(limits = c(0,1)) +
#  scale_x_continuous(breaks = seq(0, 10, by = 1)) +
  xlab("Religiosity") +
  ylab("Probability to vote for party") +
  theme_bw()
```


# Trees

```{r}
tre_ess <- mlogit_ess %>% 
  mutate(progressive_populism = ifelse(target == "Progressive Populism", 1, 0)) %>% 
  mutate(trad_populism = ifelse(target == "Traditionalist Populism", 1, 0)) %>%    
  select(progressive_populism, unemployed, anti_imm)  
  
#pacman::p_load(FFTrees)
fft_populism <- FFTrees(formula = progressive_populism ~.,
                    data = tre_ess,
                    main = "Populism",
                    decision.labels = c("Establishment", "Traditional Populism"))

plot(fft_populism)



```