---
title: "Variants of Populism"
subtitle: "Support for Populism in 22 European countries"
author: "Marlon Schumacher, Quynh Nga Nguyen & Fabio Votta"
date: "2018/06/09 <br> <br> Slides: <a href='variants-of-populism.netlify.com'>https://variants-of-populism.netlify.com/ </a>"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

<style>
.onehundredtwenty {
  font-size: 120%;
   }

<style>
.ninety {
  font-size: 90%;
   }

.eightyfive {
  font-size: 85%;
   }
   
.eighty {
  font-size: 80%;
   }
   
.seventyfive {
  font-size: 75%;
   }
   
.seventy {
  font-size: 70%;
   }
</style>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

.onehundredtwenty[

Goal:

> Examine whether public deliberation has an effect on regime legitimacy

]

---

## Outline

.onehundredtwenty[

1. Challenges in the Academic Literature
2. Mapping Progressive and Traditionalist Populists
3. Results
4. Conclusions & Future Research

]


---

class: inverse, center, middle

## Get Started


---

class: inverse, center, middle


## Conclusions

---


## Conclusions

* Account for the *multidimensionality* of extremism
    + extremism is not only limited to hate speech, it's also ideological
    
    
* Taking complaints about ambiguity of hate speech seriously

* More accountable AI programming:
    + AI deletion: problems with uncertainty and ambiguity of language
    + Need for *human in the loop*
    + Include Feedback: possibility to appeal (restricted times)
    + Algorithms must be responsive and transparent
    + Highlight content in question and reasons
    + Cross-checking algorithms to reduce error rate

---

class: inverse, center, middle


## Thanks for Listening!

**Slides:** <a href='decoding-the-altright.netlify.com'>https://decoding-the-altright.netlify.com/ </a>

**Code and Data on** <a href='https://github.com/favstats/DecodingTheAltRight'>GitHub</a>

---

## References

Hawley, G. (2017). Making Sense of the Alt-right. Columbia University Press.

Marwick, A., & Lewis, R. (2017). Media manipulation and disinformation online. New York: Data & Society Research Institute.



---

class: inverse, center, middle

## Appendix

---