---
output: pdf_document
---

## What is populist about populism? (5,5)

While populism is an important and intensely debated topic, most scholarship is plagued with conceptual conflations (Mudde/Kaltwasser 2011: 1). Despite existing pleas to avoid these, many influential scholars continue to use qualifying features of the Right to describe populism, possibly leading to severe shortcomings in their empirical analyses. To avoid similar conceptual confusions, this chapter will first adopt Cas Mudde’s clear minimalist definition to identify those core elements that all subtypes of populism have in common (2.1.1.). Subsequently, we propose a comprehensive framework to classify European populist parties along two relevant dimensions: progressivist and traditionalist populism. (2.1.2.)

### A minimalist definition: Moving away from the confusion between populism and the Right (3)

In nearly every handbook about populism, authors would eventually point out to the concept’s contested nature. As Heinisch et al. described, “[n]early as ubiquitous as articles and commentaries on populism is the assertion that it is a contested concept and difficult to define. […] [T]here have been numerous conceptualisations, which are themselves derived from several fundamental approaches that differ […] in their ideas on whether populism is primarily ideational, discursive, stylistic, or strategic in nature.” (HB: 22) This contending debate on how to best define populism is reflected by various empirical studies that emphasize different and sometimes even contradictory aspects of the phenomenon (Gerring 2001: 120 in HB: 169). Broadly speaking, there exist three types of definition for populism. It can be qualified as an organizational type, as a political communication style or as a thin ideology (cf. Pauwels 2011: 99). Especially the latter type has gained prominence in scholarly literature (? Referenz wiederfinden) However, the differentiation between populism as a communication style and as a thin ideology seems artificial at times. Both types distinguish between the people as opposed to the elite and they both allow for a combination with other (even diametrically opposed) ideologies. In our understanding these two types of populism share so many characteristics that the differentiation between them seems to be a matter of wording rather than a matter of clear defined features of populism. 

Most scholars agree on the “chameleonic” character of populism (cf. Taggart 2000 in Ot/Low 2015: 61).  Some authors, borrowing Michael Freeden’s (1996) notion of a thin ideology (in Ot/Low 2015:61), assert that populism can be combined with other more “established” 


ideologies like liberalism, nationalism, conservatism, federalism or socialism (i.e. Mudde 2015:1, M/K 2017: 19, Albertazzi & McDonnell 2008: 4). As Mudde and Kaltwasser emphasize, populism can be “left-wing or right-wing, organized in top-down or bottom-up fashion, rely on strong leaders or be even leaderless” (? In Mudde/Kaltwasser 2012: 153). 

A serious problem is therefore the confusion between populism and the Right (ie Betz, 1994 in Albertazzi & McDonnell 2008:3), as Cas Mudde laments: “Until now, populism was almost exclusively linked to the radical right, leading to an incorrect conflation of populism and xenophobia.”  (Mudde 2015: 1 in HB. 229) This tendency has to do with the fact that populism gained strength in Europe with the formation of populist radical right parties in the 1980s (Mudde/Kaltwasser 2012: 155). Their emergence triggered the blossoming of a vast scholarly literature – although focussing almost exclusively on discussing right-wing populism (De Lange, 2008, in Ot/low 2015:60) while neglecting the growing impact of their counterpart on the left side of the political spectrum (Lucardie and Voerman, 2012; March and Mudde, 2005 in Ot/Low 2015: 60).  

Despite the already existing thematization of this shortcoming, many scholars still make the mistake of using right-wing characteristics to define populism (Mudde 2007 in Ot/Low 2015: 61). Inglehart and Norris, for instance, justified their definition of populism as follows: “Cas Mudde has been influential in the literature, suggesting that populist philosophy is a loose set of ideas that share three core features: anti-establishment, authoritarianism, and nativism.” (Inglehart/Norris 2016: 6). Considering that the publication they quoted from is called “Populist Radical Right Parties in Europe” (2007), Inglehart’s and Norris’ statement seems to be remarkably negligent. In this publication, Mudde unambiguously named authoritarianism and nativism as ideological features of the populist right and not of populism per se (cf. Mudde 2007: 22, Mudde/Kaltwasser 2012: 155). We believe that it is exactly because of such a theoretical conflation that Inglehart’s and Norris’ empirical classification of European parties exhibits serious flaws, i.e. by wrongly indicating that the National Democratic Party of Germany belongs to the populist left party family, just to name but one. (cf. Inglehart/Norris 2016: 36). As Albertazzi points out, “this insistence on making ‘populist’ and ‘extreme right’ synonymous or lumping all populists under the ‘radical Right populist’ banner for ease of comparison […] is detrimental to our understanding [of] […] populism itself.” (Albertazzi et al. 2007: 4). 

To avoid similar mistakes, we draw on a minimalist definition to capture those core features that all subtypes of populism have in common. Following Mudde (who is indeed “influential in the literature”), we view populism as “a thin-centered ideology that considers society to be ultimately separated into two homogeneous and antagonistic groups, ‘the pure people’ versus  


‘the corrupt elite’, and which argues that politics should be an expression of the volonté générale (general will) of the people”. (Mudde 2004: 543) / (Mudde/Kaltwasser 2017: 6). The biggest advantage about this minimalist definition is its neutrality, allowing us to analyse populism separately from the ideological situation in which it operates (Hali/Nanou 2012: 2). 

Marlon: The essential point about Mudde’s definition is to make a normative distinction between the "pure" people and the "corrupt" elite (cf. Mudde 2017: 9). Generally speaking, the elite can be defined on the basis of power. Whatever specific group of elite, the corrupt elite is understood as a homogeneous group that works for their own interests instead of representing the volonté générale (general will of the people) (M/K 2017: 11). Therefore, the politics should be an expression of the general will (M/K 2017: 16). 

Verbinden & Reformulieren/Kürzen: In essence, “Whatever their positioning on the Left/Right spectrum, the key feature of populists is their claim to be the ‘true democrats’, fighting to reclaim the people’s sovereignty from the professional political and administrative classes (be they in regional or national capitals, or at supranational level in Brussels), as well as other elite ‘enemies’ who, through the sleight of hand of representative and deliberately arcane and complex politics, have stolen and perverted democracy.” (Albertazzi & McDonnell 2008: 4) “Populists claim that, contrary to the ruling elites, they will make good on their promises.” (Ot/Low 2015: 60). 

Recognizing that left-wing populism was widely neglected in the past, recent scholarship has started to study this variant of populism (i.e. Stavrakakis, 2014 or Rendueles, 2018). However, so far this literature has tended to conduct qualitative case studies that concentrate on regional singularities instead of generalizable tendencies of the phenomenon. 

Reformulieren/Kürzen: “Like most political phenomena, populism is studied mostly nationally and partly regionally. The first studies of populism were focused exclusively on the United States, while later work looked at Latin America and Western Europe. Few cross-regional studies of populism exist (notably Weyland 1999), while most generic studies of populism remain fairly theoretical and empirically voluntaristic (e.g., Laclau 2005; Taggart 2000). This situation is neither unique to the topic of populism nor without compelling reasons.” (Mudde/Kaltwasser 2011: 1)

Left-wing populism is commonly perceived as geographically limited to Latin America while right-wing populism is associated to the European political context. Given the recently growing importance of left-wing populist parties in Europe (i.e. SYRIZA or Podemos), it is important to study the populist phenomenon taking into account – but without limiting it to – the regional context (comprising political, cultural and economic specificities) that it is


embedded in (? in HB: 138, 229). 

With regard to the populist phenomenon in Europe – which is this is paper’s focus of study – two common points shared by all populist parties are important to note. First, as explained above, populists reject establishment parties that they consider to represent the "corrupt elite" (M/K 2017: 12). Secondly, populists are consistently opposed to the European integration process. It is however at this point that differences between varieties of populism manifest. While populists from both sides of the political spectrum display an anti-European stance, the justification and intensity of their euroskepticism vary depending on their ideological orientation (in Ot/Low 2015: 60, M/K 2017: 22). What, then, essentially distinguishes the operating logic of these populism subtypes?

### An essential distinction: Moving towards a comprehensive conceptualization of progressive and traditionalist populism (2,5)

The main difference originates from the populists’ conception of “the pure people” and “the corrupt elite”. As Mudde and Kaltwasser (2017) assert, “[e]ach populist actor emerges because of a particular set of social grievances, which influences its choice of host ideology, which in turn affects how the actor defines ‘the people’ and ‘the elite’”. (M/K 2017: 22). Populists are usually ambiguous about the “people” that they intend to represent (HB: 22). Since ‘the people’ is an “empty signifier” (Laclau in M/K 2017: 9), its meaning varies depending on historical and regional circumstances and differs from party to party (Canovan 1981 in HB: 169). Due to this ambiguity, the dichotomy between the “pure people” and the “corrupt elite” can be understood from a political, a cultural or an economic viewpoint (Mény and Surel 2000 in HB: 169). Most populists therefore not only target the political elite, but also other types of elites like the economic, the cultural or the media elite (M/K 2017: 12). 

While all populists attack political elites, left-wing populists especially target the economic elite. Right wing populists, on the other hand, are characterized by nativism and focus on “cultural antagonism” (HB:170, cf. Mudde 2007: 18 ff.). Simply put, populist parties frequently enter in a marriage of convenience with some type of ‘nativism’ on the right and with some sort of ‘socialism’ on the left” (Mudde 2015: 1 in HB: 229, M/K 2017: 21). Radical-right wing populists emphasize the necessity to resist “external threats” to the nation state. This ethno-centric tendency expresses

RIGHT: The shared ideology of radical right-wing parties is centred on nationalism. These parties highlight the need for resistance against external threats to the nation – often expressed by an ‘ethno-centric message’ (Hainsworth 2008) and tough policies on asylum and immigration (Mudde 1996, 2007; Mair & Mudde 1998). (in hali/nanou 2012: 2)


LEFT: The shared ideology of radical left-wing parties has three key elements (March & Mudde 2005): a rejection of the values of capitalism and the free market economy; the protection of collective economic and social rights in pursuit of social justice; and the idea of states working together to address shared concerns in support of internationalism.Therefore, conventionally, the defence of the nation tends to be associated with radical parties of the right 



There is a lively discussion within recent scholarship on how to ideally capture these two broad dimensions of the populist phenomenon. They are commonly labelled as “right-wing” and “left-wing” populism. Some authors prefer to describe them as 

